//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day7.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day7.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT dq -&gt; dr
        ///kg OR kf -&gt; kh
        ///ep OR eo -&gt; eq
        ///44430 -&gt; b
        ///NOT gs -&gt; gt
        ///dd OR do -&gt; dp
        ///eg AND ei -&gt; ej
        ///y AND ae -&gt; ag
        ///jx AND jz -&gt; ka
        ///lf RSHIFT 2 -&gt; lg
        ///z AND aa -&gt; ac
        ///dy AND ej -&gt; el
        ///bj OR bi -&gt; bk
        ///kk RSHIFT 3 -&gt; km
        ///NOT cn -&gt; co
        ///gn AND gp -&gt; gq
        ///cq AND cs -&gt; ct
        ///eo LSHIFT 15 -&gt; es
        ///lg OR lm -&gt; ln
        ///dy OR ej -&gt; ek
        ///NOT di -&gt; dj
        ///1 AND fi -&gt; fj
        ///kf LSHIFT 15 -&gt; kj
        ///NOT jy -&gt; jz
        ///NOT ft -&gt; fu
        ///fs AND fu -&gt; fv
        ///NOT hr -&gt; hs
        ///ck OR cl -&gt; cm
        ///jp RSHIFT 5 -&gt; js
        ///iv OR jb -&gt; jc
        ///is OR it -&gt; iu
        ///ld OR le -&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aoc7 {
            get {
                return ResourceManager.GetString("aoc7", resourceCulture);
            }
        }
    }
}
